config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users do
	  resources :profiles
  end
  resources :requests

  resources :profiles





  resources :walls do
	  resources :galleries
  end

#  resources :locations

  resources :requests do
	  resources :galleries
  end

  resources :offers


  resources :pictures



  resources :messages do
	  member do
		  post :new
	  end
	  collection do
		  get :reply
	  end
  end
  resources :conversations do
	  member do
		  get  :reply
		  post :reply
		  post :trash
		  post :untrash
	  end
	  collection do
		  get :trashbin
		  post :empty_trash
	  end
  end




end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	# GET /message/new
	def new
		@request = Request.find(params[:request])
		@message = current_user.messages.new
		@user = @request.user
	end

	def reply
		@conversation ||= current_user.mailbox.conversations.find(params[:id])
	end

	# POST /message/create
	def create
		@user = User.find(params[:user])
		@body = params[:body]
		@subject = params[:subject]
		current_user.send_message(@user, params[:body], params[:subject])
		flash[:notice] = "Message has been sent!"
		redirect_to :conversations
	end
end

app/views/messages/new.erb
Reply to post:

<h4><%=  @request.title %></h4>
<h4>From: <%= @user.email %></h4>
<%= form_tag({controller: "messages", action: "create"}, method: :post) do %>
    <%= hidden_field_tag :subject, @request.title %>
    <%= label :body, "Message text" %>
    <%= text_area_tag :body %>
    <%= hidden_field_tag(:user, "#{@user.id}") %>
    <%= submit_tag 'Send message', class: "btn btn-primary" %>
<% end %>

app/views/messages/reply.html.erb
Reply:
<%= form_for :message, url: reply_conversation_path(@conversation) do |f| %>
    <%= f.text_area :body %>
    <%= f.submit "Send Message", class: 'btn btn-primary' %>
    <%= submit_tag 'Clear Reply Box', type: :reset, class: 'btn btn-danger' %>
<% end %>