config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users do
	  resources :profiles
  end
  resources :requests

  resources :profiles





  resources :walls do
	  resources :galleries
  end

#  resources :locations

  resources :requests do
	  resources :galleries
  end

  resources :offers


  resources :pictures



  resources :messages do
	  member do
		  post :new
	  end
	  collection do
		  get :reply
	  end
  end
  resources :conversations do
	  member do
		  get  :reply
		  post :reply
		  post :trash
		  post :untrash
	  end
	  collection do
		  get :trashbin
		  post :empty_trash
	  end
  end




end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user
	has_one :location
	has_one :gallery
	validates_presence_of :gallery
	has_many :pictures, through: :gallery

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:show, :edit, :update, :destroy]

	# GET /profiles
	# GET /profiles.json
	def index
		@profiles = Profile.all
	end

	# GET /profiles/1
	# GET /profiles/1.json
	def show
		@profile  = Profile.find(params[:id])
		unless @profile.gallery.nil?
			@gallery = @profile.gallery
			@pictures = @gallery.pictures
		end
	end






	# GET /profiles/new
	def new
		@profile = Profile.new
		@gallery = @profile.build_gallery
		@pictures = @gallery.pictures
	end


	# GET /profiles/1/edit
	def edit
	end

	# POST /profiles
	# POST /profiles.json
	def create
		@profile = Profile.new profile_params
		@profile.build_gallery
		@pictures = @profile.gallery.pictures


		respond_to do |format|
			if @profile.save

				if params[:images]
					# The magic is here ;)
					params[:images].each { |image|
						@pictures.create(image: image)
					}
				end

				format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
				format.json { render :show, status: :created, location: @profile }
			else
				format.html { render :new }
				format.json { render json: @profile.errors, status: :unprocessable_entity }
			end
		end
	end


	# PATCH/PUT /profiles/1
	# PATCH/PUT /profiles/1.json
	def update
		respond_to do |format|
			if @profile.update(profile_params)
				format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
				format.json { render :show, status: :ok, location: @profile }
			else
				format.html { render :edit }
				format.json { render json: @profile.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /profiles/1
	# DELETE /profiles/1.json
	def destroy
		@profile.destroy
		respond_to do |format|
			format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_profile
		@profile = Profile.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def profile_params
		params.require(:profile).permit(:bio, :user_id, gallery_attributes: [:id, :name, :description, :profile_id]).merge(user_id: current_user.id)
	end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :multipart => true } do |f| %>





    <%= f.fields_for @profile.gallery do |ff| %>

        <div class="control-group">
          <%= ff.label :name, :class => 'control-label' %>
          <div class="controls">
            <%= ff.text_field :name, :class => 'text_field' %>
          </div>
        </div>
        <div class="control-group">
          <%= ff.label :description, :class => 'control-label' %>
          <div class="controls">
            <%= ff.text_field :description, :class => 'text_field' %>
          </div>
        </div>

        <div class="control-group">
          <%= ff.label :pictures, :class => 'control-label' %>
          <div class="controls">
            <!-- The magic is coming ...look at my eyes....shazammmm -->
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
        </div>

    <% end %>


    <div class="form-actions">
      <%= f.submit nil, :class => 'button' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  profiles_path, :class => 'button' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
  <tr>
    <th>Bio</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.bio %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>




<div class="row">

  <ul class="thumbnails files">
    <% @profile.gallery.pictures.each do |pic| %>
        <li class="span3" id="picture_<%= pic.id %>">
          <div class="thumbnail">
            <%= image_tag pic.image.url %>
            <div class="caption">
              <p style="text-align: center;">
                <%= link_to "Edit", picture_path(pic) %>

                <%=
                    link_to "Delete", pic,
                            :data => { :confirm => "Are you sure?" },
                            :method => :delete
                %>

              </p>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>