config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users do
	  resources :profiles
  end
  resources :requests

  resources :profiles





  resources :walls do
	  resources :galleries
  end

#  resources :locations

  resources :requests do
	  resources :galleries
  end

  resources :offers


  resources :pictures



  resources :messages do
	  member do
		  post :new
	  end
	  collection do
		  get :reply
	  end
  end
  resources :conversations do
	  member do
		  get  :reply
		  post :reply
		  post :trash
		  post :untrash
	  end
	  collection do
		  get :trashbin
		  post :empty_trash
	  end
  end




end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoFavorIt</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://i.icomoon.io/public/temp/4d3f767796/UntitledProject2/style.css">
</head>
<body>


<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

  <div class="container-fluid">

    <div class="pull-left ">
      <!-- <div class="nav-header">
         <div class="navlogo"></div>

         < % if user_signed_in? % >
           <div class="requestname"><strong>< %= current_user.username % ></strong></div>
       < % end % >
       </div>-->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Favors... <b class="caret"></b></a>
          <ul class="btn-group select select-block mbl">
            <li><%= link_to "View Offers", offers_path %></li>
            <li><%= link_to "Add Offer", new_offer_path %></li>
            <li><%= link_to "View Requests", requests_path %></li>
            <li><%= link_to "Add Request", new_request_path %></li>
          </ul>
        </li>
        <li><%= link_to "Inbox", conversations_path %></li>
        <li><%= link_to "Profile", profiles_path %></li>
        <li><a href="#">Help</a></li>

        <% if user_signed_in? %>
            <li class="active"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li class="active"><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>      </ul>
      <% if user_signed_in? %>


          <div class="navlogo">

          </div>
          <%= current_user.try(:email)%>


      <% end %>


      <form class="navbar-form navbar-right">
        <%= form_tag(offers_path, :method => :get) do %>
            <%= text_field_tag :search, nil,
                               {:id => "search-query-2", :placeholder => "Search offers..."} %>
            <%= hidden_field_tag :use_keywords, "true" %>
            <%= hidden_field_tag :wide_search, "true" %>
        <% end %>
      </form>
    </div>
  </div>
  <div id="headerbar2">

  </div>

</nav>

<div style="padding-top: 60px; ">

</div>

<!--<div class="logo page-header">-->

<!--</div>-->
<div class="headerbar2">
  <p class="alert alert-success"><%= notice %></p>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>
<div class="col-sm-3 col-md-2 sidebar-offcanvas well" id="sidebar" role="navigation">
  <ul class="nav nav-list">
    <li class="nav-header">Categories</li>
    <li><%= link_to "Labor", requests_path %></li>
    <li><%= link_to "Carpooling", offers_path %></li>
    <li><%= link_to "Tutoring", requests_path %></li>
    <li><%= link_to "Art", conversations_path %></li>
    <li><%= link_to "Career", conversations_path %></li>
    <li><%= link_to "Delivery", conversations_path %></li>
    <li><%= link_to "Learning", conversations_path %></li>
    <li><%= link_to "Labor", requests_path %></li>
    <li><%= link_to "Carpooling", offers_path %></li>
    <li><%= link_to "Tutoring", requests_path %></li>
    <li><%= link_to "Art", conversations_path %></li>
    <li><%= link_to "Career", conversations_path %></li>
    <li><%= link_to "Delivery", conversations_path %></li>
    <li><%= link_to "Learning", conversations_path %></li>



  </ul>

</div>


<div class="col-sm-9 col-md-10 main">
  <%= yield :scripts %>
  <%= yield %>

</div>


<footer>
  <p class="pull-right">©2014 Lunar FX</p>
</footer>

</body>
</html>